config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_closed', on: :member
  end
  
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  post 'places', to:'places#search'
  post 'places', to:'places#search'
  delete 'signout', to: 'sessions#destroy'

end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  def to_s
    "#{ name }"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beers = case order
             when 'name' then @beer_clubs.sort_by(&:name)
             when 'founded' then @beer_clubs.sort_by(&:founded)
             when 'brewery' then @beer_clubs.sort_by(&:brewery)
             end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Name</label>
    <input class="form-control" placeholder="Enter name">
  </div>

  <div class="form-group">
    <label>Founded</label>
    <input class="form-control" placeholder="Enter year">
  </div>

  <div class="form-group">
    <label>City</label>
    <input class="form-control" placeholder="Enter city">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"></p>

<h1>Beer Clubs</h1>

<%= link_to 'New Beer Club', new_beer_club_path if current_user %>
<br/>
<br/>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) if current_user %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' } if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"></p>

<h1> <%= @beer_club.name %> </h1>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<h2>Members</h2>

<ul>
  <% @beer_club.users.each do |user| %>
    <li>
      <%= link_to user.username, user %>  
    </li>
  <% end %>
</ul> 

<% if current_user %>
  <% if @beer_club.users.exclude?(current_user) %>
    <h4>Join this club:</h4>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit class:"btn btn-primary", value:"Join now" %>
    <% end %>
  <% else %>
    <%= form_for(@membership, method: "delete") do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit class:"btn btn-danger", value: "End the membership" %>
    <% end %>
  <% end %>
  <br/>
  <%= link_to 'Edit', edit_beer_club_path(@beer_club) %> |
<% end %>
<%= link_to 'Back', beer_clubs_path %>