config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_closed', on: :member
  end
  
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  post 'places', to:'places#search'
  post 'places', to:'places#search'
  delete 'signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage
  extend Top

  PASSWORD_FORMAT = /\A
    (?=.*\d)
    (?=.*[A-Z])
    /x

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30 }
  validates :password, length: { minimum: 4 },
                       format: { with: PASSWORD_FORMAT }
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships
  has_many :beer_clubs, through: :memberships
  has_secure_password

  def average
    return 0 if ratings.empty?

    ratings.map(&:score).sum / ratings.count.to_f
  end

  def to_s
    user.to_s
  end

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?

    fav_style = ""
    fav_avg = 0
    style_hash = ratings.group_by{ |r| r.beer.style }
    style_hash.each_value do |ratings|
      sum = 0
      ratings.each do |rating|
        sum += rating.score
      end
      avg = sum / ratings.size
      if avg > fav_avg
        fav_avg = avg
        fav_style = style_hash.key(ratings).name
      end
    end
    fav_style
  end

  def favorite_brewery
    return nil if ratings.empty?

    fav_brewery = ""
    fav_avg = 0
    style_hash = ratings.group_by{ |r| r.beer.brewery }
    style_hash.each_value do |ratings|
      sum = 0
      ratings.each do |rating|
        sum += rating.score
      end
      avg = sum / ratings.size
      if avg > fav_avg
        fav_avg = avg
        fav_brewery = style_hash.key(ratings)
      end
    end
    fav_brewery
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user

      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
      session.destroy
    end
  end

  def toggle_closed
    user = User.find(params[:id])
    user.update_attribute :closed, !user.closed

    new_status = !user.closed? ? "active" : "closed"

    redirect_to user, notice: "user status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :closed)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= current_user.username %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user and current_user.admin and user.frozen? %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"></p>

<p>
  <h1> <%= @user.username %> </h1>
</p>

<% if (@user.closed == true) %>
  <span class="badge badge-warning">Closed</span>
<% end %>

<% if(current_user != nil && current_user.admin == true) %>

<%= link_to "Close/unclose user", toggle_closed_user_path(@user.id), method: :post, class: "btn btn-primary" %>

<% end %>

<p>
  Has made <% @user.ratings.count %> ratings, average rating <% round(@user.average_rating) %>
</p>

<p>
  Favorite beer style: <%= @user.favorite_style %> 
</p>

<p>
  Favorite brewery: <%= @user.favorite_brewery %> 
</p>

<h2> Club Memberships </h2>

<ul>
  <% @user.beer_clubs.each do |beer_club| %>
    <li>
      <%= link_to beer_club.name, beer_club %>  
    </li>
  <% end %>
</ul> 

<h2> Ratings </h2>

<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
          <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul> 

<% if @user == current_user %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>
<% if @user == current_user %> |
<%= link_to 'Destroy', user_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>